### ISSUE TITLE
Not Able to connect to s3a on mac using version 1.32

### ISSUE THREAD

**Issue by chandresh-kraftbase** [MrYsLab/s3-extend#51] opened 2024-11-28 13:13 UTC
# S3A Websocket Connection Problem

## System Configuration

- Operating System: macOS
- Arduino Board: Arduino Uno

## Observed Behavior

- S3A service says "arduino initialized"

- Websocket connection closes immediately

- Websocket connection exits

### Backplane Startup

- Works fine, returns device IP

## ARDGW Startup

```
Pymata Express Version 1.21
Copyright (c) 2018-2020 Alan Yorinks All rights reserved.
 
Opening all potential serial ports...
	/dev/cu.usbserial-10
 
Waiting 4 seconds(arduino_wait) for Arduino devices to reset...
 
Searching for an Arduino configured with an arduino_instance =  1
 
Arduino found and connected to /dev/cu.usbserial-10
 
 
Arduino Firmware ID: 1.2 FirmataExpress.ino
Auto-discovery complete. Found 20 Digital Pins and 6 Analog Pins
 
 
Traceback (most recent call last):
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/psutil/_psosx.py", line 349, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/psutil/_psosx.py", line 406, in cmdline
    return cext.proc_cmdline(self.pid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/Users/ansh/scratch/venv/bin/ardgw", line 8, in <module>
    sys.exit(arduino_gateway())
             ^^^^^^^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/s3_extend/gateways/arduino_gateway.py", line 511, in arduino_gateway
    app = ArduinoGateway(subscriber_list, **kw_options, event_loop=loop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/s3_extend/gateways/arduino_gateway.py", line 99, in __init__
    super(ArduinoGateway, self).__init__(subscriber_list=subscriber_list,
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/python_banyan/gateway_base_aio/gateway_base_aio.py", line 119, in __init__
    super(GatewayBaseAIO, self).__init__(back_plane_ip_address=back_plane_ip_address,
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/python_banyan/banyan_base_aio/banyan_base_aio.py", line 122, in __init__
    p_command = p.cmdline()
                ^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/psutil/__init__.py", line 745, in cmdline
    return self._proc.cmdline()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/psutil/_psosx.py", line 354, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=12788)

```

# WSGW Startup
```
Traceback (most recent call last):
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/psutil/_psosx.py", line 349, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/psutil/_psosx.py", line 406, in cmdline
    return cext.proc_cmdline(self.pid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/Users/ansh/scratch/venv/bin/wsgw", line 8, in <module>
    sys.exit(ws_gateway())
             ^^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/s3_extend/gateways/ws_gateway.py", line 284, in ws_gateway
    WsGateway(subscription_list, **kw_options, event_loop=loop)
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/s3_extend/gateways/ws_gateway.py", line 79, in __init__
    super(WsGateway, self).__init__(subscriber_list=subscription_list,
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/python_banyan/banyan_base_aio/banyan_base_aio.py", line 122, in __init__
    p_command = p.cmdline()
                ^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/psutil/__init__.py", line 745, in cmdline
    return self._proc.cmdline()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ansh/scratch/venv/lib/python3.12/site-packages/psutil/_psosx.py", line 354, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=12788)

```

Additional Information
Arduino IDE running normally
No reported issues with IDE startup or functionality

**Comment by MrYsLab** [comment] 2024-11-28 17:19
Duplicate of #50

**Comment by MrYsLab** [comment] 2024-11-28 17:29
Thanks for letting me know. Due to some sloppy testing, I thought it was fixed. See this comment in issue #50 https://github.com/MrYsLab/s3-extend/issues/50#issuecomment-2506550913

**Closed by MrYsLab** 2024-11-28 17:29 UTC
Labels: duplicate
